name: uni_pay_web
description: A lightweight library for processing online payments and generating invoices with Moyasar, providing seamless payment info retrieval as well.
version: 3.0.0
repository: https://github.com/UNICODE-Venture/uni_pay_web
homepage: https://github.com/UNICODE-Venture/uni_pay_web
issue_tracker: https://github.com/UNICODE-Venture/uni_pay_web/issues
environment:
  sdk: ^3.4.0

dependencies:
  http: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
