name: uni_pay_web
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/UNICODE-Venture/uni_pay_web

environment:
  sdk: ^3.4.3

dependencies:
  http: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
